services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: agronomia_db
    ports:
      - "7300:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7301:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - phpmyadmin_data:/var/www/html
    depends_on:
      - db

  frontend:
    image: node:24-alpine
    working_dir: /app
    ports:
      - "7302:4200"
    volumes:
      - .:/app                  # Monta tu código fuente
      - /app/node_modules       # Evita sobreescribir node_modules del contenedor
    command: >
      sh -c "npm install && npx ng serve --host 0.0.0.0
             --poll 1000
             --allowed-hosts An_ProyectoAgronomia_G5"
    depends_on:
      - db

volumes:
  mysql_data:
  phpmyadmin_data:
